# Site settings
email: daniil.merkulov@skolkovotech.ru
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Awakening
description: Cozy and warm place
url: ""
twitter_username:
default_img:

# Profile settings
name: Bratishka
profile_img: /images/profile.jpg
profile: Меня зовут Даня, я люблю математику, стендап и Русь.
social:
  github: https://github.com/MerkulovDaniil/
  vk: https://vk.com/merkulov_daniil
  medium: https://medium.com/@bratishkin
  telegram: t.me/bratishk

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
