# Site settings
email: danya@merkulov.top
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"

# SEO settings
title: merkulov.top
description: cozy and warm place
url: "https://merkulov.top"
default_img: "https://merkulov.top/images/posts/180217_scientifictools/card-sm.png"

# Profile settings
name: Bratishka
profile_img: /images/profile.jpg
profile: Меня зовут Даня, я PhD студент в Сколковском Институте Науки и Технологий. Я люблю математику, преподавать, историю, путешествовать и неоднозначность бытия. Этот сайт - попытка собрать воедино то, что мне кажется или показалось важным.
social:
  github: https://github.com/MerkulovDaniil/
  vk: https://vk.com/merkulov_daniil
  twitter: https://twitter.com/danya_merkulov
  telegram: https://t.me/bratishk_skaz

# Build settings
include: ["_categories"]
exclude: [Gemfile", "Gemfile.lock", node_modules]
# Markdown settings
markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  syntax_highlighter_opts:
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
plugins: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer, jemoji]

collections:
  skaz:
    output: true