# Site settings
email: daniil.merkulov@skolkovotech.ru
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: merkulov.top
description: cozy and warm place
url: "http://www.merkulov.top"
twitter_username:
default_img: "http://www.merkulov.top/images/posts/180217_scientifictools/card-sm.png"

# Profile settings
name: Bratishka
profile_img: /images/profile.jpg
profile: Меня зовут Даня, я PhD студент в Сколковском Институте Науки и Технологий. Я люблю математику, преподавать, историю, путешествовать и неоднозначность бытия. Этот сайт - попытка собрать воедино то, что мне кажется или показалось важным.
social:
  github: https://github.com/MerkulovDaniil/
  vk: https://vk.com/merkulov_daniil
  twitter: https://twitter.com/danya_merkulov
  telegram: https://t.me/bratishk

# Build settings
include: ["_categories"]
exclude: [Gemfile", "Gemfile.lock"]
markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer, jemoji]