name: Deploy from Notion to Pages

on: [workflow_dispatch]
#  schedule:
#    - cron: "*/20 * * * *"
    
jobs:
  generate-restruct-update:
    runs-on: ubuntu-latest
    
    steps:
        # Download packages
      - name: Submodule Update
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          sudo apt-get update
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
          
      - name: Download notion4ever
        uses: actions/checkout@v2
        with:
          repository: 'MerkulovDaniil/notion4ever'
          
      - name: Install packages
        run: pip install -r requirements.txt
        
      - name: Download current version of the site
        uses: actions/checkout@v2
        with:
          repository: 'MerkulovDaniil/merkulovdaniil.github.io'
          ref: main
          path: _site
          
      - name: Run notion4ever
        run: python -m notion4ever
        env:
            NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
            NOTION_PAGE_ID: ${{secrets.NOTION_PAGE_ID}}
            
      - name: List files in the repository
        run: ls $GITHUB_WORKSPACE
      
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: _site
